### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by teppokoivula** [Toutouwai/FieldtypeDynamicOptions#5]
Hey Robin!

First of all, this module has become a very common sight on our sites. It's a brilliant tool for so many tasks. A big "thank you" is definitely in order :)

Now, since it's on use on an increasing amount of our sites, I'd really like to be able to install it via Composer. If you could set that up (composer.json and packagist.org entry), I'd be very grateful. And if it's too much hassle, just let me know and I'll set up a private fork here to keep things nice and clean. Thanks in advance!

**Comment by Toutouwai** [comment]
Hi Teppo,

Thanks for the feedback. I've added the module to Packagist.

**Comment by teppokoivula** [comment]
Awesome, thanks!
