### ISSUE TITLE
Add an option to not encode label

### ISSUE THREAD

**Issue by romaincazier** [Toutouwai/FieldtypeDynamicOptions#6]
Hi @Toutouwai,

Would it be possible to add an option to disable the encoding of the label for radios/checkboxes?

For this you have to set [`entityEncodeText`](https://github.com/processwire/processwire/blob/3cc76cc886a49313b4bfb9a1a904bd88d11b7cb7/wire/modules/Inputfield/InputfieldRadios/InputfieldRadios.module#L49) to `false` in [`getInputfield`](https://github.com/Toutouwai/FieldtypeDynamicOptions/blob/8740a46e7079572034fb57f4a1e23fe42b5c2c55/FieldtypeDynamicOptions.module#L96) (could be right after setting its name).

My use case is I would like to display blocks of colors to choose from (based on another field’s value):
<img width="1634" alt="Screenshot 2024-07-16 at 16 30 49" src="https://github.com/user-attachments/assets/076be7d3-063c-4142-9f1b-cb05472b12f5">

**Comment by Toutouwai** [comment]
I see what you're wanting to do there, but this is a Fieldtype module so I don't think it should be getting involved with settings for inputfields. Any option to have a non-default entity encoding should be a setting of the inputfield. So for your special inputfield you could extend InputfieldRadios and add a config option for entityEncodeText, or you can hook before render() or at renderReadyHook() and set that option for your particular inputfield instance.

**Comment by romaincazier** [comment]
I understand and respect your reasoning on this. I’ll go the hook route then.

Thanks for considering!
